Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

In [8]:
import numpy as np
# ADDITION
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 41 52 63 74 85]


In [9]:
# SUBRACTION
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [10]:
# multiplication
newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [ ]:
newarr = np.divide(arr1, arr2)
# division
print(newarr)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
# mod or remainder
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
# newarr = np.remainder(arr1,arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [14]:
# power
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[          1000     1280000000 19683000000000  6553600000000
           2500              0]


In [15]:
# quotient and mod 
# The return value is two arrays, 
# the first array contains the quotient
# and second array contains the mod.
newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [16]:
# absolute

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]
