In [5]:
from numpy import random
x = random.randint(100)
print(x)

20


In [7]:
x = random.rand()
print(x) # returns a random float value between 0 and 1


0.5895374944180999


Generate random array 

In [8]:
# integers
x = random.randint(100,size=(5))
print(x)

[62 21 23 26 16]


In [9]:
# Generate a 2-D array with 3 rows,
# each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))

print(x)

[[81 49 32 62 81]
 [76 86 29 68 64]
 [77 39  8 33 57]]


In [10]:
# Float
x = random.rand(5)

print(x)


[0.89829375 0.46097697 0.24638707 0.91452255 0.77383398]


In [11]:
x = random.rand(3, 5)

print(x)

[[0.17975504 0.67493795 0.37636453 0.99631622 0.69074392]
 [0.14802223 0.66366884 0.36517155 0.38098504 0.0967352 ]
 [0.32601366 0.55394848 0.55074841 0.54013571 0.44904076]]


Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [12]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [13]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 7 9 9]
 [9 7 7 7 3]
 [7 3 9 3 3]]
