In [ ]:
# it talks about the number of elements in eah dimension
# the attribute "shape" returns 
# a tuple with each index having their corresponding number of elements
import numpy as np
ar =  np.array([[1,2,3,4],[5,6,7,8]])
print(ar.shape)
# The example above returns (2, 4),
# which means that the array has 2 dimensions,
# where the first dimension has 2 elements and the second has 4.



(2, 4)


In [2]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
#The outermost dimension will have 4 arrays, each with 3 elements

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# # as long as the elements required for reshaping are equal in both shapes.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# newarr = arr.reshape(3, 3)

# print(newarr) an error is raised as:

# ValueError                                Traceback (most recent call last)
# Cell In[5], line 4
#       1 # as long as the elements required for reshaping are equal in both shapes.
#       2 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# ----> 4 newarr = arr.reshape(3, 3)
#       6 print(newarr)

# ValueError: cannot reshape array of size 8 into shape (3,3)


In [ ]:
# check if returned array is copy or view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
# since the orginal array is shown it is a view


[1 2 3 4 5 6 7 8]


# Unknown dimension - 
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr) # we cannot pass -1 to  more than 1 dimension 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays :
Flattening array means converting a multidimensional array into a 1D array.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
