In [2]:
# numpy is used on arrays
# it is called as ndarray
import numpy as np
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [3]:
type(ar)

numpy.ndarray

In [4]:
# 0 Dimesional ndarray
a2 = np.array(23)
print(a2)

23


In [5]:
# 2darray
a3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
# 3d array
a4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a4)
a4.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [ ]:
ar =  np.array([1,2,3,4],ndmin=5)
# ndmin is used to define the 
# mumber of dimension array can/is going to have
ar.ndim
# In this array the innermost dimension 
# (5th dim) has 4 elements,
# the 4th dim has 1 element that is the vector,
# the 3rd dim has 1 element that is the matrix with the vector,
# the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

5