The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [2]:
# Make a copy, change the original array, and display both arrays
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


* The copy SHOULD NOT be affected by the changes made to the original array.



In [3]:
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


* The view SHOULD be affected by the changes made to the original array.
* The original array SHOULD be affected by the changes made to the view.

In [4]:
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
x = arr.copy() # check if the array owns its data
y = arr.view()

print(x.base)
print(y.base)


None
[31  2  3  4  5]
